#spring:
#  datasource:
#      url: jdbc:mysql://m.uxuan.info:3306/cms?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#      username: root
#      password: kuwan@2017
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cms?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
#配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    multipart:
      location: D:\temp
mybatis:
   mapperLocations: classpath:/mapper/*.xml

#uploadDir: http://localhost:9520/src/assets/upload
#公司电脑上传地址
uploadDir: D:\vue
#HJ笔记本上传地址
#uploadDir: F:\Amazon\vue
server:
  port: 8090
