spring:
  datasource:
      url: jdbc:mysql://m.uxuan.info:3306/cms?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: kuwan@2017
mybatis:
   mapperLocations: classpath:/mapper/*.xml
#uploadDir: http://localhost:9520/src/assets/upload
uploadDir: F:\FINAL\vue